language: node_js

node_js:
  - 15

services:
  - docker

before_install:
  - npm install
  - npm run build
  - make login build

script:
  - make test

deploy:
  provider: script
  script: make push
  on:
    branch: master

notifications:
  slack: $SLACK_TOKEN
