language: python

services:
  - docker

before_install:
  - make login build

script:
  - make test

deploy:
  provider: script
  script: make push
  on:
    branch: master

notifications:
  slack: $SLACK_TOKEN
