version: '3.5'
services:
    django-sivusto-app:
      build: .
      image: osakunta/django-sivusto
      container_name: django-sivusto-app
      ports:
        - 8010:8010
      environment:
        - DB_HOST=django-sivusto-db
        - DB_NAME=postgres
        - DB_USER=postgres
        - DB_PASSWORD=postgres
      volumes:
        - ./sato:/usr/src/app/sato
    django-sivusto-db:
      image: postgres
      environment:
        - POSTGRES_PASSWORD=postgres
      volumes:
        - django-sivusto-db:/var/lib/postgresql/data

volumes:
  django-sivusto-db:
