version: '3.5'
services:
    django-sivusto-app:
      build: .
      image: osakunta/django-sivusto
      container_name: django-sivusto-app
      ports:
        - 8010:8010
      environment:
        - POSTGRES_HOST=django-sivusto-db
        - POSTGRES_NAME=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - DJANGO_PRODUCTION=0
        - DJANGO_SECRET_KEY=secret
      volumes:
        - ./sato:/usr/src/app/sato
    django-sivusto-db:
      image: postgres
      container_name: django-sivusto-db
      environment:
        - POSTGRES_PASSWORD=postgres
      volumes:
        - django-sivusto-db:/var/lib/postgresql/data

volumes:
  django-sivusto-db:
