version: '3'

services:
    production:
        restart: always
        environment:
            DJANGO_PRODUCTION: 1
            DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
            DJANGO_DB_PASSWORD: ${DJANGO_DB_PASSWORD}
        build:
            context: .
            dockerfile: ./Dockerfile
        command: ./bin/production.sh
        ports:
            - "8010:8010"

    test:
        restart: always
        build:
            context: .
            dockerfile: ./Dockerfile
        command: ./bin/development.sh
        ports:
            - "8011:8010"
