# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('cmsplugin_content_wrappers', '0002_contentsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentColumn',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_content_wrappers_contentcolumn', serialize=False, to='cms.CMSPlugin')),
                ('main_content', djangocms_text_ckeditor.fields.HTMLField(blank=True)),
                ('aligned_content', djangocms_text_ckeditor.fields.HTMLField(blank=True)),
                ('extra_classes', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
