kind: Service
apiVersion: v1
metadata:
  name: django-service
spec:
  selector:
    app: django
  ports:
  - protocol: TCP
    port: 8010
    targetPort: 8010
  loadBalancerIP: 192.168.1.240
  type: LoadBalancer
