# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_raw_html', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawhtmlplugin',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_raw_html_rawhtmlplugin', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
