kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: django-static-pvc
  labels:
    type: local
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: django-static-pv
