kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-static-pvc
  labels:
    type: local
spec:
  storageClassName: standard
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  volumeName: nginx-static-pv
