apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes  3;

    events {
      worker_connections  10240;
    }

    http {
      server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;

        location /static {
          alias /django/static/;
        }

        location / {
          include proxy_params;
          proxy_pass http://django-service:8010;
        }
      }
    }
