kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-static-pvc
  labels:
    type: local
spec:
  storageClassName: standard
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  volumeName: nginx-static-pv
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-media-pvc
  labels:
    type: local
spec:
  storageClassName: standard
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  volumeName: nginx-media-pv
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-smedia-pvc
  labels:
    type: local
spec:
  storageClassName: standard
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  volumeName: nginx-smedia-pv
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-gallery-pvc
  labels:
    type: local
spec:
  storageClassName: standard
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  volumeName: nginx-gallery-pv
