name: test

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install npm dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Build docker image
        run: make build

      - name: Run tests
        run: make test

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push image to Docker Hub
        if: github.ref == 'refs/heads/master'
        run: make push
