name: test

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install npm dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Run tests
        run: make test
